export const ALL_ZONES = [
    {
        key: 'yellowFigureLarge',
        x: 123,
        y: 222,
        targetKey: 'yellowFigureLarge',
        description: "Большая жёлтая фигура",
    },
    {
        key: 'yellowEllipseMedium',
        x: 496,
        y: 482,
        targetKey: 'yellowEllipseMedium',
        description: "Средний жёлтый шар",
    },
    {
        key: 'yellowEllipseSmall',
        x: 492,
        y: 334,
        targetKey: 'yellowEllipseSmall',
        description: "Малый жёлтый шар",
    },
    {
        key: 'yellowPyramidLarge',
        x: 164,
        y: 486,
        targetKey: 'yellowPyramidLarge',
        description: "Большая жёлтая пирамида",
    },
    {
        key: 'yellowEllipseLarge',
        x: 500,
        y: 410,
        targetKey: 'yellowEllipseLarge',
        description: "Большой жёлтый шар",
    },
    {
        key: 'yellowPyramidSmall',
        x: 226,
        y: 314,
        targetKey: 'yellowPyramidSmall',
        description: "Малая жёлтая пирамида",
    },
    {
        key: 'yellowPyramidMedium',
        x: 252,
        y: 370,
        targetKey: 'yellowPyramidMedium',
        description: "Средняя жёлтая пирамида",
    },
    {
        key: 'yellowCubeLarge',
        x: 544,
        y: 211,
        targetKey: 'yellowCubeLarge',
        description: "Большой жёлтый куб",
    },
    {
        key: 'yellowFigureMedium',
        x: 216,
        y: 174,
        targetKey: 'yellowFigureMedium',
        description: "Средняя жёлтая фигура",
    },
    {
        key: 'yellowCubeSmall',
        x: 558,
        y: 318,
        targetKey: 'yellowCubeSmall',
        description: "Малый жёлтый куб",
    },
    {
        key: 'yellowFigureSmall',
        x: 192,
        y: 272,
        targetKey: 'yellowFigureSmall',
        description: "Малая жёлтая фигура",
    },
    {
        key: 'yellowCubeMedium',
        x: 484,
        y: 270,
        targetKey: 'yellowCubeMedium',
        description: "Средний жёлтый куб",
    },
]