export const ALL_OBJECTS = [
    {
        key: 'greenCube',
        imageName: 'greenCube.png',
        name: 'greenCube',
        x: 377,
        y: 329,
        scale: 0.7,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'greenEllipse',
        imageName: 'greenEllipse.png',
        name: 'greenEllipse',
        x: 137,
        y: 399,
        scale: 0.7,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'greenPyramid',
        imageName: 'greenPyramid.png',
        name: 'greenPyramid',
        x: 109,
        y: 414,
        scale: 0.7,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'redCube',
        imageName: 'redCube.png',
        name: 'redCube',
        x: 574,
        y: 436,
        scale: 0.7,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'redEllipse',
        imageName: 'redEllipse.png',
        name: 'redEllipse',
        x: 380,
        y: 294,
        scale: 0.7,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'redPyramid',
        imageName: 'redPyramid.png',
        name: 'redPyramid',
        x: 311,
        y: 332,
        scale: 0.7,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'yellowCube',
        imageName: 'yellowCube.png',
        name: 'yellowCube',
        x: 609,
        y: 452,
        scale: 0.7,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'yellowEllipse',
        imageName: 'yellowEllipse.png',
        name: 'yellowEllipse',
        x: 368,
        y: 351,
        scale: 0.7,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'yellowPyramid',
        imageName: 'yellowPyramid.png',
        name: 'yellowPyramid',
        x: 548,
        y: 461,
        scale: 0.7,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
];
