export const ALL_ZONES = [
    {
        key: 'boxRequired',
        imageName: 'boxRequired.png',
        name: 'boxRequired',
        x: 184,
        y: 622,
        targetKey: ['greenCube', 'greenEllipse', 'greenPyramid'],
        scale: 0.5,
        description: 'Необходимое',
    },
    {
        key: 'boxNeeded',
        imageName: 'boxNeeded.png',
        name: 'boxNeeded',
        x: 314,
        y: 682,
        targetKey: ['yellowCube', 'yellowEllipse', 'yellowPyramid'],
        scale: 0.5,
        description: 'Нужное',
    },
    {
        key: 'boxRemove',
        imageName: 'boxRemove.png',
        name: 'boxRemove',
        x: 446,
        y: 656,
        targetKey: ['redCube', 'redEllipse', 'redPyramid'],
        scale: 0.5,
        description: 'Выбросить',
    },
];
