export const ALL_ZONES = [
    {
        key: 'boxRequired',
        imageName: 'boxRequired.png',
        name: 'boxRequired',
        x: 184,
        y: 622,
        targetKey: [
            'greenFigureLarge',
            'greenFigureMedium',
            'greenFigureSmall',
            'greenEllipseLarge',
            'greenEllipseMedium',
            'greenEllipseSmall',
            'greenPyramidLarge',
            'greenPyramidMedium',
            'greenPyramidSmall',
            'greenCubeLarge',
            'greenCubeMedium',
            'greenCubeSmall',
        ],
        scale: 0.5,
        description: "Необходимое",
    },
    {
        key: 'boxNeeded',
        imageName: 'boxNeeded.png',
        name: 'boxNeeded',
        x: 314,
        y: 682,
        targetKey: [
            'yellowFigureLarge',
            'yellowFigureMedium',
            'yellowFigureSmall',
            'yellowEllipseLarge',
            'yellowEllipseMedium',
            'yellowEllipseSmall',
            'yellowPyramidLarge',
            'yellowPyramidMedium',
            'yellowPyramidSmall',
            'yellowCubeLarge',
            'yellowCubeMedium',
            'yellowCubeSmall',
        ],
        scale: 0.5,
        description: "Нужное",
    },
    {
        key: 'boxRemove',
        imageName: 'boxRemove.png',
        name: 'boxRemove',
        x: 446,
        y: 656,
        targetKey: [
            'redFigureLarge',
            'redFigureMedium',
            'redFigureSmall',
            'redEllipseLarge',
            'redEllipseMedium',
            'redEllipseSmall',
            'redPyramidLarge',
            'redPyramidMedium',
            'redPyramidSmall',
            'redCubeLarge',
            'redCubeMedium',
            'redCubeSmall',
        ],
        scale: 0.5,
        description: "Выбросить",
    },
]