export const ALL_ZONES = [
    {
        key: 'greenEllipseSmall',
        imageName: 'greenEllipseSmallZone.png',
        x: 358,
        y: 316,
        targetKey: 'greenEllipseSmall',
        scale: 1,
        description: "Малый зелёный шар",
    },
    {
        key: 'greenEllipseMedium',
        imageName: 'greenEllipseMediumZone.png',
        x: 395,
        y: 332,
        targetKey: 'greenEllipseMedium',
        scale: 0.8,
        description: "Средний зелёный шар",
    },
    {
        key: 'greenPyramidSmall',
        imageName: 'greenPyramidSmallZone.png',
        x: 424,
        y: 350,
        targetKey: 'greenPyramidSmall',
        scale: 1,
        description: "Малая зеленая пирамида",
    },
    {
        key: 'greenFigureLarge',
        imageName: 'greenFigureLargeZone.png',
        x: 472,
        y: 382,
        targetKey: 'greenFigureLarge',
        scale: 0.8,
        description: "Большяа зелёная фигура",
    },
    {
        key: 'greenPyramidLarge',
        imageName: 'greenPyramidLargeZone.png',
        x: 547,
        y: 417,
        targetKey: 'greenPyramidLarge',
        scale: 0.8,
        description: "Большяа зелёная пирамида",
    },
    {
        key: 'greenEllipseLarge',
        imageName: 'greenEllipseLargeZone.png',
        x: 622,
        y: 469,
        targetKey: 'greenEllipseLarge',
        scale: 0.8,
        description: "Большой зелёный шар",
    },
    {
        key: 'greenPyramidMedium',
        imageName: 'greenPyramidMediumZone.png',
        x: 419,
        y: 401,
        targetKey: 'greenPyramidMedium',
        scale: 0.9,
        description: "Средняя зелёная пирамида",
    },
    {
        key: 'greenFigureMedium',
        imageName: 'greenFigureMediumZone.png',
        x: 468,
        y: 429,
        targetKey: 'greenFigureMedium',
        scale: 0.9,
        description: "Средняя зелёная фигура",
    },
    {
        key: 'greenCubeLarge',
        imageName: 'greenCubeLargeZone.png',
        x: 499,
        y: 451,
        targetKey: 'greenCubeLarge',
        scale: 1,
        description: "Большой зелёный куб",
    },
    {
        key: 'greenCubeSmall',
        imageName: 'greenCubeSmallZone.png',
        x: 143,
        y: 401,
        targetKey: 'greenCubeSmall',
        scale: 0.8,
        description: "Малый зеленый куб",
    },
    {
        key: 'greenCubeMedium',
        imageName: 'greenCubeMediumZone.png',
        x: 120,
        y: 416,
        targetKey: 'greenCubeMedium',
        scale: 0.8,
        description: "Средний зеленый куб",
    },
    {
        key: 'greenFigureSmall',
        imageName: 'greenFigureSmallZone.png',
        x: 92,
        y: 433,
        targetKey: 'greenFigureSmall',
        scale: 0.8,
        description: "Малыя зелёная фигура",
    },
]