export const ALL_OBJECTS = [
    {
        key: 'plant',
        name: 'plant',
        imageName: 'plant.png',
        x: 307,
        y: 234,
        scale: 0.08,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'documentFolder',
        name: 'documentFolder',
        imageName: 'documentFolder.png',
        x: 338,
        y: 272,
        scale: 0.2,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'packOfPaper',
        name: 'packOfPaper',
        imageName: 'packOfPaper.png',
        x: 118,
        y: 412,
        scale: 0.18,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'paperStand',
        name: 'paperStand',
        imageName: 'paperStand.png',
        x: 379,
        y: 312,
        scale: 0.2,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'pencilStand',
        name: 'pencilStand',
        imageName: 'pencilStand.png',
        x: 434,
        y: 331,
        scale: 0.1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'bottle',
        name: 'bottle',
        imageName: 'bottle.png',
        x: 123,
        y: 332,
        scale: 0.09,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'stackOfPapers',
        name: 'stackOfPapers',
        imageName: 'stackOfPapers.png',
        x: 369,
        y: 290,
        scale: 0.8,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'foodInABox',
        name: 'foodInABox',
        imageName: 'foodInABox.png',
        x: 321,
        y: 336,
        scale: 0.2,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'yellowHighlighter',
        name: 'yellowHighlighter',
        imageName: 'yellowHighlighter.png',
        x: 374,
        y: 272,
        scale: 0.1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'deskCalendar',
        name: 'deskCalendar',
        imageName: 'deskCalendar.png',
        x: 616,
        y: 440,
        scale: 0.2,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'vitamins',
        name: 'vitamins',
        imageName: 'vitamins.png',
        x: 425,
        y: 361,
        scale: 0.5,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'monoblock',
        name: 'monoblock',
        imageName: 'monoblock.png',
        x: 484,
        y: 350,
        scale: 1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'stackOfBooks',
        name: 'stackOfBooks',
        imageName: 'stackOfBooks.png',
        x: 545,
        y: 409,
        scale: 0.5,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'photoFrame',
        name: 'photoFrame',
        imageName: 'photoFrame.png',
        x: 543,
        y: 382,
        scale: 0.8,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'keyboard',
        name: 'keyboard',
        imageName: 'keyboard.png',
        x: 449,
        y: 409,
        scale: 1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'pen',
        name: 'pen',
        imageName: 'pen.png',
        x: 495, 
        y: 429,
        scale: 1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'computerMouse',
        name: 'computerMouse',
        imageName: 'computerMouse.png',
        x: 501,
        y: 443,
        scale: 1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'calculator',
        name: 'calculator',
        imageName: 'calculator.png',
        x: 376,
        y: 385,
        scale: 0.7,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'smartphone',
        name: 'smartphone',
        imageName: 'smartphone.png',
        x: 527,
        y: 466,
        scale: 0.3,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'screwdriver',
        name: 'screwdriver',
        imageName: 'screwdriver.png',
        x: 386,
        y: 312,
        scale: 0.1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'scotchTape',
        name: 'scotchTape',
        imageName: 'scotchTape.png',
        x: 649,
        y: 475,
        scale: 0.15,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'glue',
        name: 'glue',
        imageName: 'glue.png',
        x: 562,
        y: 420,
        scale: 0.2,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'glueStick',
        name: 'glueStick',
        imageName: 'glueStick.png',
        x: 407,
        y: 346,
        scale: 0.1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'tearOffNotebook',
        name: 'tearOffNotebook',
        imageName: 'tearOffNotebook.png',
        x: 108,
        y: 398,
        scale: 0.2,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'appleCore',
        name: 'appleCore',
        imageName: 'appleCore.png',
        x: 339,
        y: 356,
        scale: 0.15,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'book',
        name: 'book',
        imageName: 'book.png',
        x: 108,
        y: 408,
        scale: 0.5,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'bracelets',
        name: 'bracelets',
        imageName: 'bracelets.png',
        x: 560,
        y: 450,
        scale: 0.15,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'can',
        name: 'can',
        imageName: 'can.png',
        x: 588, 
        y: 447,
        scale: 0.15,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'cashReceipt',
        name: 'cashReceipt',
        imageName: 'cashReceipt.png',
        x: 224,
        y: 505,
        scale: 0.15,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'coffeeCup',
        name: 'coffeeCup',
        imageName: 'coffeeCup.png',
        x: 540, 
        y: 466,
        scale: 0.5,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'crumpledBallOfPaper',
        name: 'crumpledBallOfPaper',
        imageName: 'crumpledBallOfPaper.png',
        x: 265, 
        y: 496,
        scale: 0.5,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'cup',
        name: 'cup',
        imageName: 'cup.png',
        x: 459, 
        y: 436,
        scale: 0.3,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'eraser',
        name: 'eraser',
        imageName: 'eraser.png',
        x: 442, 
        y: 372,
        scale: 0.1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'glassOfWater',
        name: 'glassOfWater',
        imageName: 'glassOfWater.png',
        x: 126, 
        y: 374,
        scale: 0.4,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'key',
        name: 'key',
        imageName: 'key.png',
        x: 399, 
        y: 412,
        scale: 0.1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'loupe',
        name: 'loupe',
        imageName: 'loupe.png',
        x: 365, 
        y: 285,
        scale: 0.1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'medicalMask',
        name: 'medicalMask',
        imageName: 'medicalMask.png',
        x: 471, 
        y: 392,
        scale: 0.2,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'nuts',
        name: 'nuts',
        imageName: 'nuts.png',
        x: 628, 
        y: 483,
        scale: 0.15,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'paperClips',
        name: 'paperClips',
        imageName: 'paperClips.png',
        x: 111, 
        y: 402,
        scale: 0.15,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'pills',
        name: 'pills',
        imageName: 'pills.png',
        x: 592, 
        y: 505,
        scale: 0.15,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'pin',
        name: 'pin',
        imageName: 'pin.png',
        x: 214, 
        y: 313,
        scale: 0.15,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'pinkHighlighter',
        name: 'pinkHighlighter',
        imageName: 'pinkHighlighter.png',
        x: 92, 
        y: 409,
        scale: 0.15,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'rubiksСube',
        name: 'rubiksСube',
        imageName: 'rubiksСube.png',
        x: 583, 
        y: 482,
        scale: 0.4,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'ruler',
        name: 'ruler',
        imageName: 'ruler.png',
        x: 641, 
        y: 498,
        scale: 0.8,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'scissors',
        name: 'scissors',
        imageName: 'scissors.png',
        x: 412, 
        y: 384,
        scale: 0.1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'screw',
        name: 'screw',
        imageName: 'screw.png',
        x: 271, 
        y: 346,
        scale: 0.1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'sharpener',
        name: 'sharpener',
        imageName: 'sharpener.png',
        x: 425, 
        y: 419,
        scale: 0.1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'stapler',
        name: 'stapler',
        imageName: 'stapler.png',
        x: 271, 
        y: 274,
        scale: 0.2,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'stationeryKnife',
        name: 'stationeryKnife',
        imageName: 'stationeryKnife.png',
        x: 173, 
        y: 335,
        scale: 0.2,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'stickyNotes',
        name: 'stickyNotes',
        imageName: 'stickyNotes.png',
        x: 374, 
        y: 379,
        scale: 0.1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'teaBag',
        name: 'teaBag',
        imageName: 'teaBag.png',
        x: 548, 
        y: 498,
        scale: 0.1,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
    {
        key: 'brokenCable',
        name: 'brokenCable',
        imageName: 'brokenCable.png',
        x: 112, 
        y: 390,
        scale: 0.23,
        options: {
            isDestroyable: true,
            isInteractive: true,
        },
    },
];
