export const LIST_OF_TASKS = [
    {
        description: 'Сложи в коробку “Необходимое” следующие предметы:',
        items: [
            { name: 'paperStand', id: 1, description: 'Подставка для бумаги', done: false },
            { name: 'pencilStand', id: 2, description: 'Подставка для карандашей', done: false },
            { name: 'monoblock', id: 3, description: 'Моноблок', done: false },
            { name: 'keyboard', id: 4, description: 'Клавиатура', done: false },
            { name: 'pen', id: 5, description: 'Ручка', done: false },
            { name: 'computerMouse', id: 6, description: 'Компьютерная мышь', done: false },
            { name: 'smartphone', id: 7, description: 'Смартфон', done: false },
        ],
    },
    {
        description: 'Сложи в коробку “Нужное” следующие предметы:',
        items: [
            { name: 'plant', id: 8, description: 'Растение', done: false },
            { name: 'documentFolder', id: 9, description: 'Папка для документов', done: false },
            { name: 'packOfPaper', id: 10, description: 'Пачка бумаги', done: false },
            { name: 'stackOfPapers', id: 11, description: 'Стопка бумаг', done: false },
            { name: 'yellowHighlighter', id: 12, description: 'Жёлтый маркер', done: false },
            { name: 'deskCalendar', id: 13, description: 'Настольный календарь', done: false },
            { name: 'vitamins', id: 14, description: 'Витамины', done: false },
            { name: 'stackOfBooks', id: 15, description: 'Стопка книг', done: false },
            { name: 'photoFrame', id: 16, description: 'Фоторамка', done: false },
            { name: 'calculator', id: 17, description: 'Калькулятор', done: false },
            { name: 'screwdriver', id: 18, description: 'Отвёртка', done: false },
            { name: 'scotchTape', id: 19, description: 'Скотч', done: false },
            { name: 'glue', id: 20, description: 'Клей', done: false },
            { name: 'glueStick', id: 21, description: 'Клей-карандаш', done: false },
            { name: 'tearOffNotebook', id: 22, description: 'Отрывной блокнот', done: false },
            { name: 'book', id: 23, description: 'Книга', done: false },
            { name: 'cup', id: 24, description: 'Кружка', done: false },
            { name: 'eraser', id: 25, description: 'Ластик', done: false },
            { name: 'glassOfWater', id: 26, description: 'Стакан воды', done: false },
            { name: 'key', id: 27, description: 'Ключ', done: false },
            { name: 'loupe', id: 28, description: 'Лупа', done: false },
            { name: 'nuts', id: 29, description: 'Гайки', done: false },
            { name: 'paperClips', id: 30, description: 'Скрепки', done: false },
            { name: 'pills', id: 31, description: 'Таблетки', done: false },
            { name: 'pin', id: 32, description: 'Кнопка', done: false },
            { name: 'pinkHighlighter', id: 33, description: 'Розовый маркер', done: false },
            { name: 'rubiksСube', id: 34, description: 'Кубик Рубика', done: false },
            { name: 'ruler', id: 35, description: 'Линейка', done: false },
            { name: 'scissors', id: 36, description: 'Ножницы', done: false },
            { name: 'screw', id: 37, description: 'Шуруп', done: false },
            { name: 'sharpener', id: 38, description: 'Точилка', done: false },
            { name: 'stapler', id: 39, description: 'Степлер', done: false },
            { name: 'stationeryKnife', id: 40, description: 'Канцелярский нож', done: false },
            { name: 'stickyNotes', id: 41, description: 'Стикеры', done: false },
        ],
    },
    {
        description: 'Сложи в “Мусорное ведро” следующие предметы:',
        items: [
            { name: 'bottle', id: 42, description: 'Бутылка', done: false },
            { name: 'foodInABox', id: 43, description: 'Еда в коробке', done: false },
            { name: 'appleCore', id: 44, description: 'Огрызок яблока', done: false },
            { name: 'bracelets', id: 45, description: 'Браслеты', done: false },
            { name: 'brokenCable', id: 46, description: 'Порванный кабель', done: false },
            { name: 'can', id: 47, description: 'Банка', done: false },
            { name: 'cashReceipt', id: 48, description: 'Чек', done: false },
            { name: 'coffeeCup', id: 49, description: 'Кофейный стаканчик', done: false },
            { name: 'crumpledBallOfPaper', id: 50, description: 'Комок бумаги', done: false },
            { name: 'medicalMask', id: 51, description: 'Медицинская маска', done: false },
            { name: 'teaBag', id: 52, description: 'Чайный пакетик', done: false },
        ],
    },
];
